"""update_stock

Revision ID: ee0f967dff65
Revises: dffd3d950ba3
Create Date: 2026-05-19 18:20:40.379691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0f967dff65'
down_revision: Union[str, Sequence[str], None] = 'dffd3d950ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stock_watch', sa.Column('last_up_date', sa.String(), nullable=True))
    op.add_column('user_stock_watch', sa.Column('last_down_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stock_watch', 'last_down_date')
    op.drop_column('user_stock_watch', 'last_up_date')
    # ### end Alembic commands ###
